requires 'CPAN::DistnameInfo';
requires 'Gazelle';
requires 'HTML::Entities';
requires 'HTTP::Tiny';
requires 'Plack::Builder';
requires 'Plack::Request';
requires 'WWW::Form::UrlEncoded';
requires 'JSON::MaybeXS';
requires 'Cpanel::JSON::XS';
requires 'IO::Socket::SSL' => 1.42;
requires 'Net::SSLeay' => 1.49;
requires 'URL::Encode';
requires 'URL::Encode::XS';
requires 'Moo';
requires 'Log::Log4perl';
requires 'Log::Contextual';
test_requires 'Test::More';
test_requires 'Test::Differences';
